version: "3"
services:
  server:
    build: server/
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  client:
    build: client/
    ports:
      - 8080:80
  db:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="nh-feed"
    ports:
      - 27017:27017
